#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 19 09:48:58 2022

@author: cringwal
"""

import requests
from ratelimit import limits, RateLimitException, sleep_and_retry
import urllib.parse
import yaml

ONE_SEC = 1
MAX_CALLS_PER_SECOND = 10
MAX_call_day=200

#     earch = "artificial intelligence+Deep Learning"

# or if you want to exclude some, use the - to exclude:

#     search = "artificial intelligence-application"
############ 
# SCRIPT FOR IRAMUTEQ ANALYSIS
############


with open("/user/cringwal/home/Desktop/Scilex-main/src/scilex.config.yml", "r") as ymlfile:
    cfg = yaml.load(ymlfile)
    key=cfg["ieee"]["api_key"]



@sleep_and_retry
@limits(calls=MAX_CALLS_PER_SECOND, period=ONE_SEC)
def access_rate_limited_api(url):
    resp = requests.get(url)
    return resp

keyword="survey AND 'relation extraction'"
year=2022
keywords=urllib.parse.quote(keyword+" AND PUBYEAR = "+str(year))
ieee_url="http://ieeexploreapi.ieee.org/api/v1/search/articles?apikey="+key+"&format=json&max_records=200&sort_order=asc&sort_field=article_number&article_title="+keyword+"&publication_year="+str(year)+"&start_record={}"

page=0
has_more_pages = True
fewer_than_10k_results = True

while has_more_pages and fewer_than_10k_results:
    url = ieee_url.format(page)
    print('\n' + url)
    
    response=access_rate_limited_api(url)
    page_with_results =response.json()
    
    # loop through partial list of results
    results = page_with_results['articles']

    # next page
    page = page + 200

    has_more_pages = len(results) == 200
    total=int(page_with_results["total_records"])
    print(">>>>>",page,"/",total)
    fewer_than_10k_results = total <= 10000
    time_needed= total /100/5/60
    print("TOTAL EXTRACTION WILL NEED >",time_needed,"minutes")
    
    if(fewer_than_10k_results == False):
        print("QUERY TOO LARGE MUST BE REVIEWED")