zotero:
    api_key: "YOURAPIKEY"
google_scholar:
    api_key: "YOURAPIKEY"
springer:
    api_key: "YOURAPIKEY"
sem_scholar:
    api_key: "YOURAPIKEY"
elsevier:
    api_key: "YOURAPIKEY"
ieee:
    api_key: "YOURAPIKEY"
orcid:
    dir: 'YOURWORKDIR'
    client_id: "YOURCLIENTID"
    client_secret: "YOURAPIKEY"