# Email address for notifications or contact
email: "ollagnier@i3s.unice.fr"

# Directory to output the collected data
output_dir: 'pragmatic'

# Flag to indicate whether to collect data
collect: True

# Flag to indicate whether to aggregate data
aggregate: True

# List of years to filter the data collection  TO DO: handle range
years: [2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Keywords to use for filtering data
keywords:
  - ["NLP", "Natural Language Processing", "natural language processing"]
  - ["Dataset", "dataset", 'Benchmark', 'benchmark']

zotero:
    api_key: "YOURAPIKEY"
google_scholar:
    api_key: "YOURAPIKEY"
springer:
    api_key: "YOURAPIKEY"
sem_scholar:
    api_key: "YOURAPIKEY"
elsevier:
    api_key: "YOURAPIKEY"
ieee:
    api_key: "YOURAPIKEY"
orcid:
    dir: 'YOURWORKDIR'
    client_id: "YOURCLIENTID"
    client_secret: "YOURAPIKEY"