aggregate_txt_filter: true
aggregate_get_citations: true
aggregate_file: '/FileAggreg.csv'
apis:
- DBLP
- Arxiv
- OpenAlex
- SemanticScholar
collect: true
collect_name: graphrag
email: YOUR MAIL
fields:
- title
- abstract
keywords:
  - ["RAG", "Graphrag", "LLM", "sparql", "Multi-agent", "agent", "agentic", "Langchain", "RAG", "RAGs", "rag", "rag"]
  - ["Knowledge Graph", "Knowledge Graphs", "knowledge graph", "knowledge graph"]
output_dir: output
years:
- 2023
- 2024
- 2025

