aggregate_txt_filter: true
aggregate_get_citations: true
aggregate_file: '/SATnew.csv'
apis:
- DBLP
- Arxiv
- OpenAlex
- SemanticScholar
collect: true
collect_name: relationExtraction_SAT
email: YOUR MAIL
fields:
- title
- abstract
keywords:
- - relation extraction
- - ontology
  - context
  - prompt
output_dir: output
years:
- 2023
- 2024
- 2025

