# Email address for notifications or contact
email: "YOUR MAIL"

# Directory to output the collected data > one by collect
output_dir: 'OUTPUTDIR_path' 

# Flag to indicate whether to collect data : TO DO ADD STATS FINAL
collect: True

# Flag to indicate whether to aggregate data TO DO: DOI completion + stats
aggregate: True

# List of years to filter the data collection  TO DO: handle range
years: [2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Keywords to use for filtering data
keywords:
  - ["Survey", "state of art", "review","benchmark"]
  - ["relation extraction", "knowledge completion", 'knowledge aquisition', 'structured data extraction','fact extraction','text-to-data',"text-to-graph","complex network extraction","graph extraction"]

zotero:
    api_key: "YOURAPIKEY"
google_scholar:
    api_key: "YOURAPIKEY"
springer:
    api_key: "YOURAPIKEY"
sem_scholar:
    api_key: "YOURAPIKEY"
elsevier:
    api_key: "YOURAPIKEY"
ieee:
    api_key: "YOURAPIKEY"
orcid:
    dir: 'YOURWORKDIR'
    client_id: "YOURCLIENTID"
    client_secret: "YOUR CLIENT SECRET"
