# Email address for notifications or contact
email: "YOUR MAIL"


# Directory to output the collected data > one by collect
output_dir: 'OUTPUTDIR_path' 


# Flag to indicate whether to collect data : TO DO ADD STATS FINAL
collect: True

# Flag to indicate whether to aggregate data TO DO: DOI completion + stats
aggregate: True

# List of years to filter the data collection  TO DO: handle range

years: [2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Keywords to use for filtering data
keywords:
  - ["Conversation", "conversation", "Conversations", "conversations", "dialog", "Dialog", "Conversational", "conversational", "Dialogue", "dialogue", "chat", "Chat"]
  - ["Knowledge Graph", "Knowledge Graphs", "knowledge graph", "knowledge graph"]


# available APIs: "DBLP", "Arxiv", "Elsevier", "IEEE", "Springer", "Semantic Scholar", "OpenAlex", "HAL", "ISTEX", "Google Scholar"
apis: [DBLP, Google Scholar]

# available lookup fields: title, abstract, full text, authors
fields: [title, abstract]
