aggregate_txt_filter: true
aggregate_get_citations: true
aggregate_file: '/FileAggreg.csv'
apis:
- DBLP
- Arxiv
- OpenAlex
- SemanticScholar
collect: true
collect_name: $COLLECT_NAME$
email: YOUR MAIL
fields:
- title
- abstract
keywords:
  - ["Conversation", "conversation", "Conversations", "conversations", "dialog", "Dialog", "Conversational", "conversational", "Dialogue", "dialogue", "chat", "Chat"]
  - ["Knowledge Graph", "Knowledge Graphs", "knowledge graph", "knowledge graph"]
output_dir: output
years:
- 2023
- 2024
- 2025

