aggregate_txt_filter: false
aggregate_get_citations: false
aggregate_file: '/DatasetSurveys.csv'
apis:
- DBLP
- Arxiv
- OpenAlex
- Elsevier
- IEEE
- SemanticScholar
- Springer
collect: true
collect_name: relationExtraction_new
email: YOUR MAIL
fields:
- title
- abstract
keywords:
- - relation extraction
  - triplet extraction
  - graph extraction
output_dir: output
years:
- 2023
- 2024
-

